-- require("plugins-setup")
-- require("plugins.lualine")
-- require("plugins.telescope")
-- require("plugins.nvim-tree")
-- require("plugins.comment")
-- require("plugins.treesitter")
-- require("plugins.undotree")
require("core.keymaps")
require("core.options")
require("core.ui")
require("core.disabletex")
require("config.lazy")
